import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { FC, PropsWithChildren, ReactElement } from 'react';

const inter = Inter({ subsets: [ 'latin' ] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout: FC<PropsWithChildren> = ({
  children,
}: PropsWithChildren): ReactElement => {
  return (
    <html lang='en'>
      <body className={ inter.className }>{children}</body>
    </html>
  );
};

export default RootLayout;
